title: 欢迎使用
subtitle: 个人导航站点

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: home

categories:
  - name: 个人网站
    icon: fas fa-star
    sites:
      - name: 个人博客
        url: https://enoch.host/
        icon: fas fa-blog
        description: 我的个人博客
  - name: CTF在线工具
    icon: fas fa-wrench
    sites:
      - name: JSON Editor
        url: https://jsoneditoronline.org
        icon: fas fa-code-branch
        description: JSON在线编辑器
      - name: Notion
        url: https://www.notion.so
        icon: fas fa-sticky-note
        description: 团队协作与笔记工具
      - name: DNSlog
        url: https://eyes.sh/
        icon: fas fa-tools
        description: DNSlog
      - name: requestrepo
        url: https://requestrepo.com/
        icon: fas fa-tools
        description: DNSlog
      - name: SageMathCell
        url: https://sagecell.sagemath.org/
        icon: fas fa-calculator
        description: 在线sage
      - name: Compiler Explorer
        url: https://godbolt.org/
        icon: fas fa-code
        description: 在线编程语言编译器
      - name: libc search
        url: https://libc.blukat.me/
        icon: fas fa-code
        description: 查询libc版本
      - name: ASCII转换工具
        url: https://www.rapidtables.org/zh-CN/convert/number/ascii-hex-bin-dec-converter.html
        icon: fas fa-code
        description: 在线ASCII转换工具
      - name: JWT工具
        url: https://www.bejson.com/jwt/
        icon: fas fa-code
        description: 在线JWT解码工具
      - name: crackstation
        url: https://crackstation.net/
        icon: fas fa-key
        description: hash破解工具
      - name: CTF Tools下载
        url: https://cdisk.imxbt.cn/s/jRfM?path=%2F
        icon: fas fa-download
        description: 各种CTF常用工具合集
  - name: 实用工具
    icon: fas fa-cogs
    sites:
      - name: 在线AI人声分离
        url: https://vocalremover.org/zh/splitter-ai
        icon: fas fa-music
        description: 在线AI人声分离
      - name: B站视频下载
        url: https://6li6.com/bilibili#/
        icon: fas fa-video
        description: 在线B站视频下载工具
      - name: 极核getShell
        url: https://get-shell.com/
        icon: fas fa-terminal
        description: 网络安全工具分享
      - name: IP工具箱
        url: https://ipcheck.ing/
        icon: fas fa-search
        description: 在线IP工具
      - name: 科技爱好者周刊
        url: https://github.com/ruanyf/weekly/
        icon: fas fa-newspaper
        description: 科技爱好者周刊，issue里面有很多工具
      - name: LINUX DD
        url: https://linux.do/
        icon: fab fa-linux
        description: 技术社区
      - name: CodeInWord
        icon: fas fa-code  
        url: https://www.codeinword.com
        description: 简单好用的代码高亮工具（可以用于Word）
      - name: Remix
        icon: fas fa-ethereum  
        url: https://remix.ethereum.org/
        description: 以太坊智能合约在线编译与调试环境  
  - name: AI
    icon: fas fa-robot
    sites:
      - name: ChatGPT
        url: https://chatgpt.com/
        icon: fas fa-robot
        description: GPT！
      - name: Google Gemini 2.5 Pro
        url: https://aistudio.google.com/prompts/new_chat?model=gemini-2.5-pro
        icon: fas fa-robot
        description: Google Gemini 2.5 Pro  
      - name: Grok
        url: https://grok.com/
        icon: fas fa-robot
        description: Grok
      - name: deepseek元宝
        url: https://yuanbao.tencent.com/
        icon: fas fa-robot
        description: 腾讯元宝版deepseek
  - name: 网络安全社区
    icon: fas fa-shield-alt
    sites:
      - name: Seebug
        url: https://www.seebug.org/
        icon: fas fa-bug
        description: 国内知名漏洞平台
      - name: Freebuf
        url: https://www.freebuf.com/
        icon: fas fa-newspaper
        description: 国内知名网络安全媒体
      - name: Vulmon
        url: https://vulmon.com/
        icon: fas fa-search
        description: 漏洞搜索引擎
      - name: Hack The Box
        url: https://www.hackthebox.com/
        icon: fas fa-laptop-code
        description: 网络安全实战平台
      - name: TryHackMe
        url: https://tryhackme.com/
        icon: fas fa-laptop-code
        description: 网络安全实战平台
      - name: 先知社区
        url: https://xz.aliyun.com/
        icon: fas fa-users
        description: 网络安全技术交流社区
  - name: 云服务平台
    icon: fas fa-cloud
    sites:
      - name: Cloudflare
        url: https://www.cloudflare.com
        icon: fas fa-cloud
        description: 赛博大善人
      - name: Azure
        url: https://portal.azure.com/
        icon: fab fa-microsoft
        description: 微软云平台
      - name: 阿里云
        url: https://www.aliyun.com
        icon: fab fa-alipay
        description: 阿里巴巴云计算平台
      - name: 腾讯云
        url: https://cloud.tencent.com
        icon: fab fa-qq
        description: 腾讯云计算平台
      - name: 樱雨云
        url: https://www.ipxr.cn
        icon: fas fa-cloud-rain
        description: 图一乐，保不准跑路了
      - name: 慈云数据
        url: https://www.zovps.com/
        icon: fas fa-database
        description: 高性能云服务器
      - name: DK盾
        url: https://www.dkdun.cn/
        icon: fas fa-shield-alt
        description: 林枫云
      - name: racknerd
        url: https://www.racknerd.com/
        icon: fas fa-server
        description: 美国VPS 
      - name: namesilo
        url: https://www.namesilo.com/
        icon: fas fa-globe
        description: 域名注册商
      - name: DigitalOcean
        url: https://cloud.digitalocean.com/
        icon: fas fa-cloud
        description: Github学生包会送200美金